wandb_version: 1

input_size:
  desc: null
  value: 5
hidden_size1:
  desc: null
  value: 5
hidden_size2:
  desc: null
  value: 3
output_size:
  desc: null
  value: 3
dropout_p:
  desc: null
  value: 0.5
lr:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 20
device:
  desc: null
  value: cpu
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712273332.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 1
      - 2
      - 13
      - 16
      - 23
      - 61
      4: 3.11.4
      5: 0.16.6
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
